---
- name:
  package:
    name:
      - hyprland
      - hyprcursor
      - hyprlauncher
    state: present
  tags: [client]

- name: Create Hyprland config directory
  file:
    path: "/home/{{ target_user }}/.config/hypr"
    state: directory
  tags: [client]

- name: Remove existing Hyprland config links
  file:
    path: "/home/{{ target_user }}/.config/hypr/{{ item }}"
    state: absent
  loop:
    - hyprland.conf
    - hyprland.lua
    - modules
  tags: [client]
  become: yes

# - name: Hyprland config symlink
#   file:
#     src: "/home/{{ target_user }}/.dotfiles/roles/hyprland/files/conf/hyprland.conf"
#     dest: "/home/{{ target_user }}/.config/hypr/hyprland.conf"
#     state: link
#     force: yes
#   tags: [client]
#   become: yes

- name: Symlink Hyprland lua entry point
  file:
    src: "{{ role_path }}/files/lua/hyprland.lua"
    dest: "/home/{{ target_user }}/.config/hypr/hyprland.lua"
    state: link
    force: yes
  tags: [client]
  become: yes

- name: symlink hyprland lua modules
  file:
    src: "{{ role_path }}/files/lua/modules"
    dest: "/home/{{ target_user }}/.config/hypr/modules"
    state: link
    force: yes
  tags: [client]
  become: yes

- name: insstall xdg-desktop-portal
  package:
    name:
      - xdg-desktop-portal-hyprland
      - xdg-desktop-portal-gtk
    state: present
  become: yes
  tags: [client]
