---
# ===========================================
#  Dotfiles Playbook v2
# ===========================================
#
# Nutzung:
#   ansible-playbook pb/playbook-v2.yml -t btop -e op=remove          # entfernt btop
#   ansible-playbook pb/playbook-v2.yml -l arch_book                  # deployed alles auf arch_book
#   ansible-playbook pb/playbook-v2.yml -t nvim                       # deployed nvim
#   ansible-playbook pb/playbook-v2.yml -t btop -e install_tuis=true  # installiert btop, auch wenn außerhalb des scopes vom host
#
# Variablen kommen aus:
#   - group_vars/all/main.yml (defaults)
#   - group_vars/gui.yml
#   - group_vars/headless.yml                                          # legt fest welche roles installiert werden können
#   - inventory.yml (pro Host überschreibbar)

- name: Setup dotfiles
  hosts: all
  become: no

  tasks:
    # --- clis ---
    - name: CLI roles
      when: install_clis
      tags: [cli]
      block:
        - import_role:
            name: nvim
          tags: [nvim]
        - import_role:
            name: btop
          tags: [btop]

    # --- tuis ---

    # --- guis ---
    - name: GUI roles
      when: install_guis
      tags: [gui]
      block:
        - import_role:
            name: hyprland
          tags: [hyprland, hypr]
        - import_role:
            name: awww
          tags: [awww]
        - import_role:
            name: kitty
          tags: [kitty]
          # statusbar
        - import_role:
            name: waybar
          tags: [waybar]
        # - import_role:
        #     name: ashell ## 0 config
        #   tags: [ashell]
