---
# - name: Install collections
#   hosts: localhost
#   connection: local
#   gather_facts: yes

#   tasks:
#     - name: Install AUR collection (Arch only)
#       ansible.builtin.command:
#         cmd: ansible-galaxy collection install kewlfft.aur
#       when: ansible_facts['os_family'] == 'Archlinux'
#       changed_when: false

#     - name: Refresh facts after collection install
#       meta: refresh_inventory

- name: Setup dotfiles
  hosts: all
  become: yes
  # TODO: automatische erkennung des ausführenden users! --> default(ansible_facts['user_id']) funktionert nicht!!!
  #  vars:
  #    target_user: "{{ target_user | default(ansible_facts['user_id']) }}"
  roles:
    - git
    - gh-cli
    - yay
    - nerdfonts
    - brave
    - zsh
    - ashell
    - hyprland
    - hyprlock
    # - nvim
    - lazygit
    - kitty
    - ssh
    - waybar
    - swaync
    - ags
    - btop
    - onlyoffice
    - rofi
    - nextcloud-client
    - yazi
    - unzip
    - screenshots
    - beets
    - bluetui
    - mpd
    - moonlight
    - steam
    - modemmanager
    # - tmux
    - feishin
